version: "3.8"

services: 
  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 5001:5001
    volumes: 
      - ./api:/app

  db:
    image: mysql:5.7.35
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    ports: 
      - 3306:3306
    volumes:
      - temp_sensor:/data/db

volumes:
  temp_sensor: